server:
  port: 8080 # 服务端口

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka/ # 服务注册中心地址

spring:
  application:
    name: city-client # 服务名称

#如何为get请求，发送参数为一个对象则需要开启下面的注解，同时要引入pom文件
#feign:
#  httpclient:
#   enabled: true